### ISSUE TITLE
I wonder where I could find the implementation of vectorize_sentence

### ISSUE THREAD

**Issue by happygirlzt** [WM-SEMERU/SecureReqNet#1]
Hi, danaderp.  Many thanks for your work. I have a question, in the notebook "alpha_securereqnet
.ipynb", there is a line `from vectorize_sentence import Embeddings`, but I cannot figure out where to import this module. Is it possible that you did not upload this file? Thanks for your help! Best regards!

**Comment by rmclanton** [comment]
Hi happygirlzt. I don't know if you still need this, but the documentation can be found at https://wm-semeru.github.io/SecureReqNet/utils.html The Embeddings class is now a part of the SecureReqNet package, which is on pip. You can import this module using from securereqnet.utils import Embeddings.
